### ISSUE TITLE
Can't ping raw IP addresses

### ISSUE THREAD

**Issue by SeerLite** [Gedsh/InviZible#232]
* I'm using only DNSCrypt
* InviZible Pro v6.4.0 from FDroid
On Termux doing:

```
ping 1.2.3.4
```
will hang.
Replace `1.2.3.4` with any valid address (local or not) and the same will happen. InviZible will show a yellow line in the DNSCrypt log which I assume means it has been blocked.

I expect to be able to ping local IP addresses, without blacklisting them. I only want to have domain names encrypted.

Thank you for InviZible!

**Comment by Gedsh** [comment]
This was fixed in version 2.1.5

**Comment by SeerLite** [comment]
Hi, I just tried the app again and still have this issue on the latest F-Droid Beta, 2.4.6.

Using only DNSCrypt (default config, no tor, no i2p), I can't connect via TCP to any IP directly (I don't really care about ICMP).
